# railway.toml - Configuração para deploy do Kaneo no Railway

#
# Configuração do Backend
#
[services.backend]
name = "kaneo-backend"

# Usar imagem pré-construída em vez de construir do Dockerfile
[services.backend.image]
name = "ghcr.io/usekaneo/api:latest"

# Variáveis de ambiente
[services.backend.envs]
JWT_ACCESS = "change_me"
DB_PATH = "/app/apps/api/data/kaneo.db"

# Configuração de rede
[services.backend.ports]
http = "1337:1337"

# Configuração do volume
[[services.backend.volumes]]
path = "/app/apps/api/data"
mount_path = "/app/apps/api/data"
type = "volume"

# Comando de inicialização explícito e política de reinicialização
[services.backend.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node /app/apps/api/dist/main.js"

#
# Configuração do Frontend
#
[services.frontend]
name = "kaneo-frontend"

# Usar imagem pré-construída
[services.frontend.image]
name = "ghcr.io/usekaneo/web:latest"

# Variáveis de ambiente
[services.frontend.envs]
KANEO_API_URL = "http://kaneo-backend.railway.internal:1337"

# Configuração de rede
[services.frontend.ports]
http = "80:80"

# Comando de inicialização explícito e política de reinicialização
[services.frontend.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
startCommand = "nginx -g 'daemon off;'"